seed_number: 19941201
exp_name: '240805_test'
train:
  model_name: 'Efficientnet'
  data_augmentation: 'static-last' # 'static-last'
  data_sampling: 'random-negative-sampling'
  loss: 'Clip_Loss'
  num_epochs: 10
  optimizer:
    name: 'Adam'
    learning_rate: 5e-5
    betas: (0.9,0.98)
    eps: 1e-6
    weight_decay: 0.2
  batch_size: 64
  num_workers: 8

test:
  per_epoch: 1
  batch_size: 1
  num_workers: 0


